import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'doc',
      id: 'tutorial',
      label: 'Tutorial',
    },
    {
      type: 'doc',
      id: 'technical-overview',
      label: 'Technical Overview',
    },
    {
      type: 'category',
      label: 'Schema API Reference',
      items: [
        {
          type: 'autogenerated',
          dirName: 'schema',
        },
      ],
    },
  ],
};

export default sidebars;
