import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'doc',
      id: 'tutorial',
      label: 'Tutorial',
    },
    {
      type: 'doc',
      id: 'technical-overview',
      label: 'Technical Overview',
    },
    {
      type: 'category',
      label: 'Schema Reference',
      items: [
        {
          type: 'doc',
          id: 'Schema/grants',
          label: 'Grants System',
        },
        {
          type: 'category',
          label: 'Rule Types',
          items: [
            {
              type: 'autogenerated',
              dirName: 'Schema/Rules',
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
