name: Deploy App!

on:
  push:
    paths:
      - 'apps/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: npx install

      - name: Build repository
        run: npx build

      - name: Run each repo's deploy script
        run: npx deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
