name: Application Deployment

on:
  workflow_dispatch:
  push:
    paths:
      - '**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build repository
        run: npm run build

      # hacky and should fix this. env token needs to be used in this command directly
      - name: Run each repo's deploy script, pass in fb token
        run: npm run deploy -- -- $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
